config/routes.rb
Rails.application.routes.draw do
  # get 'courses/index'
  # get 'courses/show'
  # get 'courses/new'
  # get 'courses/create'
  # get 'courses/edit'
  # get 'courses/update'
  # get 'courses/destroy'
  # get 'interests/index'
  # get 'interests/show'
  # get 'interests/new'
  # get 'interests/edit'
  # get 'interests/update'
  # get 'interests/destory'
  # get 'instructors/index'
  # get 'instructors/show'
  # get 'instructors/destroy'
  # get 'instructors/update'
  # get 'instructors/new'
  # get 'instructors/edit'
  # get 'students/index'
  # get 'students/create'
  # get 'students/new'
  # get 'students/show'
  # get 'students/destroy'
  # get 'students/update'
  # get 'students/edit'

  resources :instructors do # /instructors
    resources :courses # /instructors/1/courses
  end

  resources :courses do # /instructors
    resources :students # /instructors/1/courses
  end

  resources :students do
    resources :interests
  end
  
  # resources :students
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'instructors#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3 }

  belongs_to :instructor
  has_many :students
end

app/models/instructor.rb
class Instructor < ApplicationRecord
  validates :firstname, presence: true, length: { minimum: 3 }
  validates :lastname, presence: true, length: { minimum: 3 }
  validates :gender, presence: true, length: { minimum: 4 }
  validates :email, presence: true, length: { minimum: 4 }
  validates :age, presence: true, length: { maximum: 3 }
  validates :phonenumber, presence: true, length: { minimum: 8 }

  has_many :courses
  # has_many :students, through: :courses

  has_and_belongs_to_many :students
end

app/models/interest.rb
class Interest < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3 }
  
  belongs_to :student
end

app/models/student.rb
class Student < ApplicationRecord
  validates :firstname, presence: true, length: { minimum: 3 }
  validates :lastname, presence: true, length: { minimum: 3 }
  validates :gender, presence: true, length: { minimum: 4 }
  validates :email, presence: true, length: { minimum: 4 }
  validates :age, presence: true, length: { maximum: 3 }
  validates :phonenumber, presence: true, length: { minimum: 8 }

  belongs_to :course
  has_many :interests
  
  has_and_belongs_to_many :instructors
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :new_course, only: [:new, :create]
  before_action :set_course, only: [:show, :edit]
  def index
    @courses = Course.all
  end

  def show
  end

  def new
    @course = @instructor.courses.build
  end

  def create
    @course = @instructor.courses.build(course_params)
    if @course.save
      redirect_to instructor_path(@instructor)
    else
      render :new      
    end
  end

  def edit
    @instructor = Instructor.find(params[:instructor_id])
  end

  def update
    @course = Course.find(params[:id])
    instructor = Instructor.find(params[:instructor_id])
    
    if @course.update(course_params)
      redirect_to instructor_path(instructor)
    else
      render :edit      
    end
  end

  def destroy
    @course = Course.find(params[:id]).destroy
    instructor = Instructor.find(params[:instructor_id])
    redirect_to instructor_path(instructor)
  end

  private
  
  def new_course
    @instructor = Instructor.find(params[:instructor_id])
  end

  def set_course
    @course = Course.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:name, :instructor_id)
  end
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  before_action :set_instructor, only: [:show, :edit, :destroy, :update]
  def index
    @instructors = Instructor.all
  end

  def show
    @instructor = Instructor.find(params[:id])
  end

  # GET
  def new
    @instructor = Instructor.new
  end

  # POST
  def create
    @instructor = Instructor.new(instructor_params)
    if @instructor.save
      redirect_to instructors_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @instructor = Instructor.find(params[:id])
    if @instructor.update(instructor_params)
      redirect_to instructors_path
    else
      render :edit      
    end
  end

  def destroy
    @instructor = Instructor.find(params[:id])
    if @instructor.destroy
      redirect_to instructors_path
    else
      render :show
    end
  end

  private
  
  def set_instructor
    @instructor = Instructor.find(params[:id])
  end

  def instructor_params
    params.require(:instructor).permit(:firstname, :lastname, :gender, :email, :age, :phonenumber)
  end
end

app/controllers/interests_controller.rb
class InterestsController < ApplicationController
  before_action :new_interest, only: [:new, :create]
  before_action :set_interest, only: [:show, :edit]

  def index
    @interests = Interest.all
  end

  def show
  end

  def new
    @interest = @student.interests.build
    #NV+
  end

  def create
    @interest = @student.interests.build(interest_params)

    if @interest.save 
      redirect_to student_path(@student)
    else
      render :new
    end
  end

  def edit
    @student = Student.find(params[:student_id])
  end

  def update
    @interest = Interest.find(params[:id])
    student = Student.find(params[:student_id])
    if @interest.update(interest_params)
      redirect_to student_path(student)
    else
      render :edit
    end
  end

  def destroy
    Interest.find(params[:id]).destroy
    student = Student.find(params[:student_id])
    redirect_to student_path(student)
  end

  private

  def new_interest
    @student = Student.find(params[:student_id])
  end
  def set_interest
    @interest = Interest.find(params[:id])
  end

  def interest_params
    params.require(:interest).permit(:name, :student_id)
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :new_student, only: [:new, :create]
  before_action :set_student, only: [:show, :edit]

  def index
    @students = Student.all
  end

  def show
    # no need to put anything coz of private set_student
    # @instructor = Instructor.find(params[:instructor_id])
    # student = Student.find(params[:id])
  end

  def new
    @student = @course.students.build
  end

  def create
    @student = @course.students.build(student_params)
    if @student.save
      redirect_to course_path(@course)
    else
      render :new      
    end
  end

  def edit
    @course = Course.find(params[:course_id])
  end

  def update
    @student = Student.find(params[:id])
    course = Course.find(params[:course_id])
    if @student.update(student_params)
      redirect_to course_path(course)
    else
      render :edit      
    end
  end
  
  def destroy
    @student = Student.find(params[:id]).destroy
    course = Course.find(params[:course_id])
    redirect_to course_path(course)
  end

  private
  
  def new_student
    @course = Course.find(params[:course_id])
  end

  def set_student
    @student = Student.find(params[:id])
  end

  def student_params
    params.require(:student).permit(:firstname, :lastname, :gender, :email, :age, :phonenumber, :course_id, instructor_ids: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/helpers/interests_helper.rb
module InterestsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/courses/_form.html.erb
<div class="container">
  <% if @course.errors.any? %>
      <%= pluralize(@course.errors.count, "error") %>
    <% @course.errors.full_messages.each do |message| %>
      <div class="alert alert-danger"> <%= message %> </div>
    <% end %>
  <% end %>
  <%= form_for [@instructor, @course] do |f| %>
    <div class="form-row">
      <%= f.label :name, "Course Name: " %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    
    <%= f.submit "Submit", class: "btn btn-primary"%>
  <% end %>
</div>

app/views/courses/create.html.erb
<h1>Courses#create</h1>
<p>Find me in app/views/courses/create.html.erb</p>

app/views/courses/edit.html.erb
<h1>Courses#edit</h1>
<p>Find me in app/views/courses/edit.html.erb</p>

<%= render "courses/form" %>

app/views/courses/index.html.erb
<h1>Courses#index</h1>
<p>Find me in app/views/courses/index.html.erb</p>

app/views/courses/new.html.erb
<h1>Courses#new</h1>
<p>Find me in app/views/courses/new.html.erb</p>

<%= render "courses/form" %>

app/views/courses/show.html.erb
<h1>Courses#show</h1>
<p>Find me in app/views/courses/show.html.erb</p>
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h3><%= @course.name %></h3>
    </div>
    <div class="col-md-6">
      <%= link_to "Add Student", new_course_student_path(@course), class: "btn btn-secondary" %>
      <table class="table mt-4">
        <tr>
          <td>id</td>
          <td>firstname</td>
          <td>lastname</td>
          <td>gender</td>
          <td>email</td>
          <td>age</td>
          <td>phone number</td>
        </tr>
        <% @course.students.each do |student| %>
          <tr>
            <td><%= link_to student.id, student_path(student.id) %></td>
            <td><%= student.firstname %></td>
            <td><%= student.lastname %></td>
            <td><%= student.gender %></td>
            <td><%= student.email %></td>
            <td><%= student.age %></td>
            <td><%= student.phonenumber %></td>
            <td>
              <%= link_to "Edit", edit_course_student_path(@course, student), class: "btn btn-warning" %>

              <%= link_to "Delete", course_student_path(@course, student), method: "DELETE", data:{ confirm: "Confirm?"}, class: "btn btn-danger" %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/courses/update.html.erb
<h1>Courses#update</h1>
<p>Find me in app/views/courses/update.html.erb</p>

app/views/instructors/_form.html.erb
<div class="container">
  <% if @instructor.errors.any? %>
      <%= pluralize(@instructor.errors.count, "error") %>
    <% @instructor.errors.full_messages.each do |message| %>
      <div class="alert alert-danger"> <%= message %> </div>
    <% end %>
  <% end %>
  <%= form_for @instructor do |f| %>
    <div class="form-row">
      <%= f.label :firstname, "First Name: " %>
      <%= f.text_field :firstname, class: "form-control" %>
    </div>
    <div class="form-row">
      <%= f.label :lastname, "Last Name: " %>
      <%= f.text_field :lastname, class: "form-control" %>
    </div>
    <div class="form-row">
      <%= f.label :gender, "Gender: " %>
      <%= f.text_field :gender, class: "form-control" %>
    </div>
    <div class="form-row">
      <%= f.label :email, "Email: " %>
      <%= f.text_field :email, class: "form-control" %>
    </div>
    <div class="form-row mb-3">
      <%= f.label :age, "Age: " %>
      <%= f.text_field :age, class: "form-control" %>
    </div>
    <div class="form-row">
      <%= f.label :phonenumber, "Phone Number: " %>
      <%= f.text_field :phonenumber, class: "form-control" %>
    </div>
    
    <%= f.submit "Submit", class: "btn btn-primary"%>
  <% end %>
</div>

app/views/instructors/edit.html.erb
<h1>Instructors#edit</h1>
<p>Find me in app/views/instructors/edit.html.erb</p>

<%= render "instructors/form" %>

app/views/instructors/index.html.erb
<h1>Instructors#index</h1>
<p>Find me in app/views/instructors/index.html.erb</p>

<div class="container">
  <%= link_to "Add Instructor", new_instructor_path, class: "btn btn-secondary" %>
  <table class="table mt-4">
    <tr>
      <td>id</td>
      <td>firstname</td>
      <td>lastname</td>
      <td>gender</td>
      <td>email</td>
      <td>age</td>
      <td>phone number</td>
    </tr>
    <% @instructors.each do |instructor| %>
      <tr>
        <td><%= link_to instructor.id, instructor_path(instructor) %></td>
        <td><%= instructor.firstname %></td>
        <td><%= instructor.lastname %></td>
        <td><%= instructor.gender %></td>
        <td><%= instructor.email %></td>
        <td><%= instructor.age %></td>
        <td><%= instructor.phonenumber %></td>
        <td>
          <%= link_to "Edit", edit_instructor_path(instructor), class: "btn btn-warning" %>

          <%= link_to "Delete", instructor_path(instructor), method: "DELETE", data:{ confirm: "Confirm?"}, class: "btn btn-danger" %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/instructors/new.html.erb
<h1>Instructors#new</h1>
<p>Find me in app/views/instructors/new.html.erb</p>

<%= render "instructors/form" %>

app/views/instructors/show.html.erb
<h1>Instructors#show</h1>
<p>Find me in app/views/instructors/show.html.erb</p>
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h3><%= @instructor.firstname %> <%= @instructor.lastname %></h3>
      <h3><%= @instructor.gender %></h3>
      <h3><%= @instructor.email %></h3>
      <h3><%= @instructor.age %></h3>
      <h3><%= @instructor.phonenumber %></h3>
    </div>
    <div class="col-md-6">
    <%= link_to "Add Course", new_instructor_course_path(@instructor), class: "btn btn-secondary" %>
      <table class="table mt-4">
        <tr>
          <td>id</td>
          <td>course name</td>
        </tr>
        <% @instructor.courses.each do |course| %>
          <tr>
            <td><%= link_to course.id, course_path(course.id) %></td>
            <td><%= course.name %></td>
            <td>
              <%= link_to "Edit", edit_instructor_course_path(@instructor, course), class: "btn btn-warning" %>

              <%= link_to "Delete", instructor_course_path(@instructor, course), method: "DELETE", data:{ confirm: "Confirm?"}, class: "btn btn-danger" %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/instructors/update.html.erb
<h1>Instructors#update</h1>
<p>Find me in app/views/instructors/update.html.erb</p>

app/views/interests/_form.html.erb
<div class="container">
  <% if @interest.errors.any? %>
      <%= pluralize(@interest.errors.count, "error") %>
    <% @interest.errors.full_messages.each do |message| %>
      <div class="alert alert-danger"> <%= message %> </div>
    <% end %>
  <% end %>
  <%= form_for [@instructor, @student, @interest] do |f| %>
    <div class="form-row">
      <%= f.label :name, "Interest Name: " %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    
    <%= f.submit "Submit", class: "btn btn-primary"%>
  <% end %>
</div>

app/views/interests/edit.html.erb
<h1>Interests#edit</h1>
<p>Find me in app/views/interests/edit.html.erb</p>

<%= render "interests/form" %>

app/views/interests/index.html.erb
<h1>Interests#index</h1>
<p>Find me in app/views/interests/index.html.erb</p>

<div class="container">
  <%= link_to "Add Interest", new_interest_path, class: "btn btn-secondary" %>
  <table class="table mt-4">
    <tr>
      <td>id</td>
      <td>name</td>
    </tr>
    <% @interests.each do |interest| %>
      <tr>
        <td><%= link_to interest.id, interest_path(interest) %></td>
        <td><%= interest.firstname %></td>
        <td>
          <%= link_to "Edit", edit_interest_path(interest), class: "btn btn-warning" %>

          <%= link_to "Delete", interest_path(interest), method: "DELETE", data:{ confirm: "Confirm?"}, class: "btn btn-danger" %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/interests/new.html.erb
<h1>Interests#new</h1>
<p>Find me in app/views/interests/new.html.erb</p>

<%= render "interests/form" %>

app/views/interests/show.html.erb
<h1>Interests#show</h1>
<p>Find me in app/views/interests/show.html.erb</p>

<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h3><%= @interest.name %></h3>
    </div>
  </div>
</div>

app/views/interests/update.html.erb
<h1>Interests#update</h1>
<p>Find me in app/views/interests/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instructors / Students / Interests</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/_form.html.erb
<div class="container">
<% if @student.errors.any? %>
      <%= pluralize(@student.errors.count, "error") %>
    <% @student.errors.full_messages.each do |message| %>
      <div class="alert alert-danger"> <%= message %> </div>
    <% end %>
  <% end %>
  <%= form_for [@course, @student] do |f| %>
    <div class="form-row">
      <%= f.label :firstname, "First Name: " %>
      <%= f.text_field :firstname, class: "form-control" %>
    </div>
    <div class="form-row">
      <%= f.label :lastname, "Last Name: " %>
      <%= f.text_field :lastname, class: "form-control" %>
    </div>
    <div class="form-row">
      <%= f.label :gender, "Gender: " %>
      <%= f.text_field :gender, class: "form-control" %>
    </div>
    <div class="form-row">
      <%= f.label :email, "Email: " %>
      <%= f.text_field :email, class: "form-control" %>
    </div>
    <div class="form-row mb-3">
      <%= f.label :age, "Age: " %>
      <%= f.text_field :age, class: "form-control" %>
    </div>
    <div class="form-row">
      <%= f.label :phonenumber, "Phone Number: " %>
      <%= f.text_field :phonenumber, class: "form-control" %>
    </div>
    
    <div class="form-row">
      <%= collection_check_boxes(:student, :instructor_ids, Instructor.all, :id, :firstname) %>
    </div>

    <div class="form-row">
      <%= f.submit "Submit", class: "btn btn-primary"%>
    </div>
  <% end %>
</div>

app/views/students/create.html.erb
<h1>Students#create</h1>
<p>Find me in app/views/students/create.html.erb</p>

app/views/students/edit.html.erb
<h1>Students#edit</h1>
<p>Find me in app/views/students/edit.html.erb</p>

<%= render "students/form" %>

app/views/students/index.html.erb
<h1>Students#index</h1>
<p>Find me in app/views/students/index.html.erb</p>

<div class="container">
  <%= link_to "Add Student", new_student_path, class: "btn btn-secondary" %>
  <table class="table mt-4">
    <tr>
      <td>id</td>
      <td>firstname</td>
      <td>lastname</td>
      <td>gender</td>
      <td>email</td>
      <td>age</td>
      <td>phone number</td>
    </tr>
    <% @students.each do |student| %>
      <tr>
        <td><%= link_to student.id, student_path(student) %></td>
        <td><%= student.firstname %></td>
        <td><%= student.lastname %></td>
        <td><%= student.gender %></td>
        <td><%= student.email %></td>
        <td><%= student.age %></td>
        <td><%= student.phonenumber %></td>
        <td>
          <%= link_to "Edit", edit_student_path(student), class: "btn btn-warning" %>

          <%= link_to "Delete", student_path(student), method: "DELETE", data:{ confirm: "Confirm?"}, class: "btn btn-danger" %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/students/new.html.erb
<h1>Students#new</h1>
<p>Find me in app/views/students/new.html.erb</p>

<%= render "students/form" %>

app/views/students/show.html.erb
<h1>Students#show</h1>
<p>Find me in app/views/students/show.html.erb</p>

<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h3><%= @student.firstname %> <%= @student.lastname %></h3>
      <h3><%= @student.gender %></h3>
      <h3><%= @student.email %></h3>
      <h3><%= @student.age %></h3>
      <h3><%= @student.phonenumber %></h3>
      <%#= link_to "Back to Instructor", instructor_path(@student.instructor_id), class: "btn btn-info" %>
    </div>
    <div class="col-md-6">
      <div>
        <%= link_to "New Interest", new_student_interest_path(@student), class: "btn btn-secondary" %>
      </div>
        <table class="table mt-4">
          <tr>
            <td>id</td>
            <td>interest name</td>
            <td>action</td>
          </tr>
          <% @student.interests.each do |interest| %>
            <tr>
              <td>
                <%= link_to interest.id, student_interest_path(@student.id, interest.id) %>
              </td>
              <td><%= interest.name %></td>
              <td>
                  <%= link_to "Edit", edit_student_interest_path(@student, interest), class: "btn btn-warning" %>
              <%= link_to "Delete", student_interest_path(@student, interest), method: "delete", data:{ confirm: "are you sure to delete this interest record?"}, class:"btn btn-danger" %>
              </td>
            </tr>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/students/update.html.erb
<h1>Students#update</h1>
<p>Find me in app/views/students/update.html.erb</p>